### ISSUE TITLE
cannot grant permission

### ISSUE THREAD

**Issue by nitipit** [callowayproject/django-objectpermissions#2]
I try to grant permission by scripting in ./manage shell
after import all Models
user.grant_object_perm(post,'o')
## i got this error log :

TypeError                                 Traceback (most recent call last)

/home/nitipit/project/shopping-project/shopping/<ipython console> in <module>()

/usr/lib/python2.6/site-packages/objectpermissions/registration.pyc in grant_object_perm(self, instance, perm)
     60             the_permission = instance.user_perms_set.get(user=self)
     61         except UserPermission.DoesNotExist:
---> 62             the_permission = instance.user_perms_set.create(user=self)
     63     elif isinstance(self, Group):
     64         try:

/usr/lib/python2.6/site-packages/django/contrib/contenttypes/generic.pyc in create(self, **kwargs)
    272             kwargs[self.content_type_field_name] = self.content_type
    273             kwargs[self.object_id_field_name] = self.pk_val
--> 274             return super(GenericRelatedObjectManager, self).create(**kwargs)
    275         create.alters_data = True
    276 

/usr/lib/python2.6/site-packages/django/db/models/manager.pyc in create(self, **kwargs)
    136 
    137     def create(self, **kwargs):
--> 138         return self.get_query_set().create(**kwargs)
    139 
    140     def filter(self, _args, *_kwargs):

/usr/lib/python2.6/site-packages/django/db/models/query.pyc in create(self, **kwargs)
    348         obj = self.model(**kwargs)
    349         self._for_write = True
--> 350         obj.save(force_insert=True, using=self.db)
    351         return obj
    352 

TypeError: save() got an unexpected keyword argument 'using'

**Comment by justquick** [comment]
What version of django are you using?

**Comment by washingtontimes** [comment]
I'm guessing you are using Trunk or 1.2 alpha/beta. We'll have to add that kwarg in the save method. I should have a fix up soon.

**Comment by nitipit** [comment]
yub, ^^ :

**Comment by washingtontimes** [comment]
Should be fixed in commit http://github.com/washingtontimes/django-objectpermissions/commit/00c916a5e321f301ef7b76760cc467e5dd9e907d

**Comment by nitipit** [comment]
Thank you ^^
