### ISSUE TITLE
Problem using admin with Django 1.1.1

### ISSUE THREAD

**Issue by rossjones** [callowayproject/django-objectpermissions#3]
It looks like line 105 in models.py is passing too many parameters to save (I assume this is a fix for 1.2) so that the 'using' parameter is causing problems.  Removing that parameters allows it to work as expected.

The line is currently:
super(Permission, self).save(force_insert, force_update, using)

changing to:
super(Permission, self).save(force_insert, force_update)

allows it to work with 1.1.1

**Comment by washingtontimes** [comment]
yea there was a problem w/ hardcoded parameters anyway. here is what the line looks like now:

super(Permission, self).save(_a, *_kw)
