### ISSUE TITLE
cannot import name auto_adapt_to_methods

### ISSUE THREAD

**Issue by cato-** [callowayproject/django-objectpermissions#5]
I am getting the above error when trying to use the decorator with django 1.2. This seems to be caused by this change:

> http://code.djangoproject.com/changeset/12399

More Info:

Django Version:     1.2.1
Exception Type:     ImportError
Exception Value:    cannot import name auto_adapt_to_methods
Exception Location:     ..../objectpermissions/decorators.py in <module>, line 11

**Comment by coordt** [comment]
Commit http://github.com/washingtontimes/django-objectpermissions/commit/e034004e15dff5baa6b43c254e6089740da469d3 should fix this and be backwards-compatible. Please let me know if this works
