### ISSUE TITLE
No permissions should return empty list for list type functions

### ISSUE THREAD

**Issue by alexkuhl** [callowayproject/django-objectpermissions#6]
Currently the functions get_object_perm_as_[str_list, int_list, choices] return 0 when there are no permissions on an object rather than an empty list.  This makes things awkward, such as when using a template you can't simply use a for...empty because Django will throw an error about int not being iterable.  Additionally, because they are functions that return lists when there are permissions, returning an empty list would be more consistent.

**Comment by coordt** [comment]
Fixed in version 0.3.3. Thanks for noticing and bringing to our attention.
